In [17]:
import pandas as pd

In [18]:
gsheetid = "1PwzQ6ZuoQaaNjPJ0yHiTIeFUKX1n1LN7gg5k9auNFXU"
sheet_name = "Data"

In [19]:
gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

In [20]:
gsheet_url

'https://docs.google.com/spreadsheets/d/1PwzQ6ZuoQaaNjPJ0yHiTIeFUKX1n1LN7gg5k9auNFXU/gviz/tq?tqx=out:csv&sheet=Data'

In [21]:
df = pd.read_csv(gsheet_url)

In [22]:
df

   col1 col2
0     1    a
1     2    b
2     3    c